CGATOxford/cgat

CGATPipelines/PipelineMapping.py, CGATPipelines/pipeline_mapping.py, CGATPipelines/pipeline_mapping/pipeline.ini
Branch adds the butter mapper to pipeline_mapping.py & PipelineMapping.py
Butter is an iterative wrapper of bowtie for small RNA mapping
=> Ts adding butter to pipeline mapping

CGATPipelines/PipelinePreprocess.py, CGATPipelines/pipeline_readqc.py, CGATPipelines/pipeline_readqc/pipeline.ini
Added cutadapt to the readqc pipeline.
=> Kb add cutadapt to readqc pipeline

CGAT/Sra.py, CGATPipelines/PipelineMapping.py, CGATPipelines/PipelinePreprocess.py, CGATPipelines/pipeline_mapping.py, CGATPipelines/pipeline_readqc.py
Changes implemented:
1. Created Sra module with functions to extract from short read archive files and identify the expected outfiles
2. Refactored PipelineMapping to use Sra module
3. Added file format checks for Butter mapper to raise a NotImplementedError when given paired reads
4. Added file format checks for preprocessing reads to raise a NotImplementedError when given non-fastq formatted reads
5. Tidied up PipelinePreprocess
=> Ts create sra module file

CGATPipelines/PipelinePreprocess.py, CGATPipelines/pipeline_readqc.py, CGATPipelines/pipeline_readqc/pipeline.ini, scripts/runExpression.py
1. automatic removal of adapter sequences can be switched on in the config file
2. implement adapter sequence removal from fasta file for trimmomatic and cutadapt
3. cutadapt version requirement >= 1.7.1
=> Mm fastqc parser adapter dictionary

CGATPipelines/PipelinePreprocess.py, CGATPipelines/PipelineRrbs.py, CGATPipelines/pipeline_readqc.py, CGATPipelines/pipeline_rrbs.py
1. Debugged pipeline preprocess to identify paired end fastqs
2. Recoded function to read in flat file to pandas dataframe to identify column data types prior to reading into memory
=> Ts debugging pipeline preprocess sickle

scripts/_bam2bam.pyx, scripts/_bams2bam.pyx
Fixes to cython code  for pysam 0.8.2.1
=> fixes for pysam 0.8.2.1

scripts/data2resamples.py, scripts/diffgene2venn.py, scripts/distance2clusters.py, scripts/distance2merge.py, scripts/expression2distance.py, scripts/expression2expression.py, scripts/timeseries2diffgenes.py
update to account for CGAT.Timeseries refactoring
=> fix import errors for issue #171

scripts/fastq2fastq.py, scripts/gff2bed.py, scripts/gtf2gtf.py
* Added 3' trimming to fastq2fastq.py
* Added gene_biotype as option for setting name in gff2bed.py
=> Ts gff2 bed add gene biotype naming option

.travis.yml, install-CGAT-tools.sh
Included new option on Travis to test a minimal Conda environment against the production scripts.
=> Slv testing suite for production scripts

scripts/_bam2geneprofile.pyx
=> fixes for missing getTotal in BAM couter

CGAT/Counts.py, CGAT/Expression.py, doc/Makefile, scripts/bed2plot.py, scripts/counts2counts.py, scripts/counts2table.py
minor refactoring of Expression.py
=> Ah expression design

CGAT/Counts.py, CGAT/Expression.py
The branch passes the STYLE, CMDLINe and PRODUCTION_SCRIPTS tests in Travis. I assume the others are all failing due to the problems with Conda in Travis? I've also run the regression tests locally and they're all OK.
The major changes in the branch relate to differential expression analysis with Sleuth.
=> Ts add methods to counts

CGAT/BamTools.py
Better estimation of insert size from RNA-seq data
=> add "convergence" estimator

scripts/fasta2fasta.py, scripts/split_file.py
Two updates to allow the splitting up of fasta files:
The first allows the filtering of fasta files on a the basis of a list of IDs.
The second adds the ability to specify a chunks size in split_file, so that several records can be output into the same file.
=> Is splitting fasta

CGAT/Peptides2Cds.py, scripts/fasta2fastq.py, scripts/peptides2cds.py
=> Ts restore peptides2cds

CGAT/Genomics.py
Functions are required for the pipeline_annotations function "buildCDSFasta" to execute
=> Add functions back to Genomics.py to pipeline_annotations.py

CGAT/Counts.py, CGAT/Expression.py, scripts/counts2table.py
Minor updates to the code in Counts.py and Expression.py
=> Ts improve sleuth de objects

CGAT/Expression.py
Corrected column index read from output by deseq2 which I hard-coded previously. 
R dataframe seems to be automatically converted to pandas dataframe now so I removed the ri2py command, which was failing.
=> Kb debugging for pipeline windows

scripts/extract_stats.py, scripts/fastq2tpm.py
Remove CGATPipeline module dependencies from extract_stats.py and fastq2tpm.py
=> Mm ac sc qc script

CGAT/BamTools.py
Added a function to Bamtools to check if a bam file has been stripped of sequence.
=> added isStripped function

scripts/bed2table.py
bed2table now allows the option of passing a sequence to search within bed regions
=> added option to search for a motif

R/metagenomic_diversity.R, scripts/cgat_fasta2cDNA.py, scripts/extract_stats.py, scripts/lca2table.py, tests/lca2table.py/taxa_counts.tsv
added metagenome_diversity.R script.
=> added metagenome_diversity.R

CGAT/Expression.py, scripts/counts2table.py
DESeq2 was not performing LRT differential testing properly due to a bug in the coding in Expression.py. This branch resolves the issue
=> Ts debug expression de seq2

CGAT/CSV2DB.py
Reffering to wrong option in CSV2DB quick load option
=> IS CSV2DB dataname name option wrong. 

CGAT/GTF.py, scripts/combine_tables.py
so that common intron intervals can be found
=> Allowed toIntronChunks to take mutiple transcripts 

scripts/fasta2unique_kmers.py
One can now count unique kmers at the gene level using fasta2unique_kmers.py (yipee!)
=> adds gene-level kmer counting fo fastq2unique kmers

CGAT/Biomart.py, scripts/runMEDIPS.py
The MEDIPs R package has various options for reads mapped with bwa which I have added.  I also added the option to select a subset of chromosomes to run through the package  and added the "unique" paramter to remove PCR duplicates.
=> Kb bwa option run medips

CGAT/Fastq.py
QUAL scores including the upper and lower bound values, previous check did not include upper bound value.
=> Fix qual score range check

scripts/fastq2tpm.py
This is to merge in any remaining single cell QC-related scripts/changes prior to the Python 3 migration
=> merge single cell QC scripts into master repository

install-CGAT-tools.sh
=> Slv installation script

CGAT/Database.py
(basestring catches both str and unicode objects).
=> Fix Database.py to recognise unicode strings 

CGAT/scripts/gff2gff.py
Ultimately this branch ended up being a very small documentation change. Jakub and I will make  branch together to implement the main script code changes
=> Have added documentation for sanitize method

CGAT/GFF3.py, CGAT/scripts/gtf2tsv.py
Have added gff3 functionality in this script.
=> Ac gff3 modify

CGAT/Expression.py, CGAT/scripts/counts2table.py
Changes to go with CGATPipelines PR#340
=> Development of DEXSeq methods

CGAT/GO.py
=> Fix go.py extra (an extension on Steve's PR)
